services:
  input-rtmp-1:
    image: tiangolo/nginx-rtmp
    container_name: input-rtmp-1
    ports:
      - "1933:1935"
    networks:
      - rtmp-net
  input-rtmp-2:
    image: tiangolo/nginx-rtmp
    container_name: input-rtmp-2
    ports:
      - "1934:1935"
    networks:
      - rtmp-net

  output-rtmp-1:
    image: tiangolo/nginx-rtmp
    container_name: output-rtmp-1
    ports:
      - "1935:1935"
    networks:
      - rtmp-net

  output-rtmp-2:
    image: tiangolo/nginx-rtmp
    container_name: output-rtmp-2
    ports:
      - "1936:1935"
    networks:
      - rtmp-net

  output-rtmp-3:
    image: tiangolo/nginx-rtmp
    container_name: output-rtmp-3
    ports:
      - "1937:1935"
    networks:
      - rtmp-net

  output-rtmp-4:
    image: tiangolo/nginx-rtmp
    container_name: output-rtmp-4
    ports:
      - "1938:1935"
    networks:
      - rtmp-net

  ffmpeg-source:
    image: linuxserver/ffmpeg
    container_name: ffmpeg-source
    depends_on:
      - input-rtmp-1
      - input-rtmp-2
    volumes:
      - ./testdata:/testdata:ro
    entrypoint: [
      "sh", "-c",
      "ffmpeg -stream_loop -1 -re -i /testdata/testsrc.mp4 -c:v libx264 -f flv rtmp://input-rtmp-1/live/stream & \
       ffmpeg -stream_loop -1 -re -i /testdata/testsrc.mp4 -c:v libx264 -f flv rtmp://input-rtmp-2/live/stream && wait"
    ]
    networks:
      - rtmp-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - rtmp-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
    networks:
      - rtmp-net
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - rtmp-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - rtmp-net

networks:
  rtmp-net:
    driver: bridge
